%function [filenames] = patch_ext_file_identifier(th_path, extras_direc)
%this function uses timestamps to identify and pair up THacq patch data
%files with the appropriate RaccPre, RaccPost and findThresh files.


%THacq_direc = 'D:\Data\Janelia\Patch\Data_MM\thacq_files\';
th_path = 'D:\Data\Janelia\Patch\Data_MM\thacq_files\20160727_cell2.mat';
extras_direc = 'D:\Data\Janelia\Patch\Data_MM\';
 
th_info = dir(th_path);
th_time = th_info.datenum;                                     %timestamp of last modification to th file.
th_time = datevec(th_time,'mmmm dd, yyyy HH:MM:SS');


extras_info = dir(extras_direc);
n_ex_files = size(extras_info, 1);
t_diff_vec = zeros(n_ex_files, 1) + nan;

%looping through each extras file
for ex_file_n = 3:n_ex_files                                %starting from 3 because the first two are the .'s generated by dir
    %skipping directories
    if extras_info(ex_file_n).isdir == 1
        continue
    else
    end
    
    curr_ex_time = extras_info(ex_file_n).datenum;             %timesampt of last modification to current ex file.
    curr_ex_time = datevec(curr_ex_time,'mmmm dd, yyyy HH:MM:SS');
    t_diff_vec(ex_file_n) = etime(curr_ex_time, th_time);      %vector of time differences between TH file and all extra files' last modifications
    

end


%end