function [] = raster_plot(cell_data, spike_data, stim_mat, odor_n, odor_dur)
%This function creates a raster plot and a PSTH curve for a given cell, for
%a given odor_n and odor_dur. 
%cell_data contains all data for the current cell, as generated by THacq
%Spike_data containes the spike times for each trial, as generated by THview_v4. 
%stim mat has n_rows = n_trials, col1 is odor_n, col 2 is odor_dur, col3 is
%odor onset time.

keyboard


end