function [aligned_mat] = xcorr2_aligner(align_mat, c)
%This function shifts the contents of a matrix (align_mat) as per the lags generated by
%xcorr2 (c) when cross correlating it with a reference matrix. The re-aligned
%matrix is of the same size as the original matrix, datapoints that fall
%outside the matrix due to the shift are discarded. Empty points are filled
%in with Nans.
%Mehrab Modi, 20140929


[maxr, maxcol] = find(c == max(max(c)));

col_lag = size(align_mat, 1) - maxr;
row_lag = size(align_mat, 2) - maxcol;

%moving align_mat as per lags detected
if sign(row_lag) == -1
    align_mat(:, ( (end-abs(row_lag) +1 ):end)) = [];
    pad = zeros(size(align_mat, 1), abs(row_lag) );
    align_mat = [pad, align_mat];
elseif sign(row_lag) == 1
    align_mat(:, 1:(abs(row_lag))) = [];
    pad = zeros(size(align_mat, 1), abs(row_lag) );
    align_mat = [align_mat, pad];
elseif sign(row_lag) == 0
end

if sign(col_lag) == -1
    align_mat( ( (end-abs(col_lag)+1):end), :) = [];
    pad = zeros(abs(col_lag), size(align_mat, 2) );
    align_mat = [pad; align_mat];
elseif sign(col_lag) == 1
    align_mat(1:(abs(col_lag)), :) = [];
    pad = zeros(abs(col_lag), size(align_mat, 2) );
    align_mat = [align_mat; pad];
elseif sign(col_lag) == 0
end

aligned_mat = align_mat;
end